# -*- coding: utf-8 -*-
"""assignment_4march19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11wFmVYgNs-3nvMo6p8NRPJJoi_WqF4B0

Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.
"""

import plotly.graph_objects as go
import seaborn as sns

titanic = sns.load_dataset("titanic")
fig = go.Figure()
fig.add_trace(go.Scatter(x=titanic["age"],y=titanic["fare"], mode= "markers"))
fig.show()

"""Q2:Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import plotly.express as px
tips = px.data.tips()
fig = px.box(tips, x="day", y="total_bill", color="smoker")
fig.update_layout(title="Total Bill by Day and Smoker Status",
                  xaxis_title="Day of the Week",
                  yaxis_title="Total Bill")
fig.show()

"""Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.
"""

tips = px.data.tips()
fig = px.histogram(tips, x="sex", y="total_bill", color="day", barmode="group", 
                    pattern_shape="smoker", category_orders={"day": ["Thur", "Fri", "Sat", "Sun"]})
fig.show()

"""This will create a histogram with the sex column on the x-axis, total_bill on the y-axis, and day as the color parameter. The smoker column will be used with the pattern_shape parameter to create different patterns for smokers and non-smokers. The category_orders parameter is used to ensure that the days of the week are ordered correctly.

Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.
"""

iris = px.data.iris()
fig = px.scatter_matrix(iris, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],
                        color="species")
fig.show()

"""This will create a scatter matrix plot with four dimensions (sepal length, sepal width, petal length, and petal width), where each dimension is plotted against every other dimension. The color parameter is set to species, which will use the species column to color-code the points in the scatter plot

Q5. What is Distplot? Using Plotly express, plot a distplot.
"""

import plotly.express as px
df = px.data.gapminder()
fig = px.histogram(df, x="lifeExp", nbins=30, opacity=0.5)
fig.show()

